### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zesheng666** [om-ai-lab/OVDEval#1]
Hello, author, your work is excellent. I have a question. How is Figure 5 drawn? Can you tell me some details, especially Figure (b)?

**Comment by chunxindangyang** [comment]
Thank you for your interest in our work. Figure 5 is plotted as follows:

First, the Intersection over Union (IoU) is calculated sequentially for each ground truth bounding box (bbox) in each image and the predicted bounding boxes of that image.

Then, if the IoU is greater than or equal to 0.9 and the label of the predicted bbox matches the label of the ground truth bbox, the prediction score is recorded as the positive score. If the IoU is less than 0.9 and the label of the predicted bbox differs from that of the ground truth, the prediction score is recorded as the negative score.

Finally, the histogram distributions of the positive and negative scores from all the images are counted and plotted to obtain Figure 5.

**Comment by Zesheng666** [comment]
Can I add your WeChat account? I have some detailed questions I would like to ask







杨泽生



南方科技大学/学生/研究生/2022级研究生



广东省深圳市南山区学苑大道1088号




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Dec 29, 2023 10:46 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [om-ai-lab/OVDEval] question (Issue #1)

&nbsp;



 
Thank you for your interest in our work. Figure 5 is plotted as follows:
 
First, the Intersection over Union (IoU) is calculated sequentially for each ground truth bounding box (bbox) in each image and the predicted bounding boxes of that image.
 
Then, if the IoU is greater than or equal to 0.9 and the label of the predicted bbox matches the label of the ground truth bbox, the prediction score is recorded as the positive score. If the IoU is less than 0.9 and the label of the predicted bbox differs from that of the ground truth, the prediction score is recorded as the negative score.
 
Finally, the histogram distributions of the positive and negative scores from all the images are counted and plotted to obtain Figure 5.

**Comment by KingSan666888** [comment]
**Thank you again for your interest in our work! If you have any further questions, you can ask them here.**

Figure 5 is plotted as follows:

First, the Intersection over Union (IoU) is calculated sequentially for each ground truth bounding box (bbox) in each image and the predicted bounding boxes of that image.

Then, if the IoU is greater than or equal to 0.9 and the label of the predicted bbox matches the label of the ground truth bbox, the prediction score is recorded as the positive score. If the IoU is less than 0.9 and the label of the predicted bbox differs from that of the ground truth, the prediction score is recorded as the negative score.

Finally, the histogram distributions of the positive and negative scores from all the images are counted and plotted to obtain Figure 5.

**Comment by Zesheng666** [comment]
作者你好，能不能给我发一份Grounding DINO 在你们数据集的测试代码，我这边调试有些问题，急急急







杨泽生



南方科技大学/学生/研究生/2022级研究生



广东省深圳市南山区学苑大道1088号




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jan 4, 2024 05:51 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [om-ai-lab/OVDEval] question (Issue #1)

&nbsp;



 
Thank you again for your interest in our work! If you have any further questions, you can ask them here.
 
Figure 5 is plotted as follows:
 
First, the Intersection over Union (IoU) is calculated sequentially for each ground truth bounding box (bbox) in each image and the predicted bounding boxes of that image.
 
Then, if the IoU is greater than or equal to 0.9 and the label of the predicted bbox matches the label of the ground truth bbox, the prediction score is recorded as the positive score. If the IoU is less than 0.9 and the label of the predicted bbox differs from that of the ground truth, the prediction score is recorded as the negative score.
 
Finally, the histogram distributions of the positive and negative scores from all the images are counted and plotted to obtain Figure 5.
