### ISSUE TITLE
Issue about the dataset

### ISSUE THREAD

**Issue by ztc20011103** [om-ai-lab/OVDEval#3]
Hi, I noticed there is no category column in material.json and color.json in annotations. May I ask if the category and category id of these two types of images corresponds to all the text and neg_text of these images? I read in your paper that you have assigned 36 text labels to color. What is the specific id of these text labels?

**Comment by P3ngLiu** [comment]
![image](https://github.com/user-attachments/assets/5199efe2-653e-4906-bfe2-1f3a32a8ca48)
https://huggingface.co/datasets/omlab/OVDEval/tree/main
Hi, Could you please check the annotation json for material and color in our huggingface dataset? I think they should have categries column with category_ids.

**Comment by ztc20011103** [comment]
Many thanks for your help! I didn't check it carefully before and I found the categories by scripts later by the way. I appreciate your work, really make sense to me!

**Comment by ztc20011103** [comment]
Many thanks for your help! I didn't check it carefully before and I found the categories by scripts later by the way. I appreciate your work, really make sense to me!
